[supervisord]
nodaemon=true
user=root
minfds=0
pidfile=/tmp/supervisord.pid

[program:hf-cloud-sync]
command=/bin/bash /usr/local/bin/backup-sync.sh
autorestart=true
priority=1

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile
autorestart=true
priority=10

[program:gost]
command=gost -config /etc/gost/gost.json
autorestart=false
priority=10

[program:gotty]
command=gotty -w -p 8085 --path /terminal/ --title-format "Ubuntu Container Shell" /bin/bash
autorestart=true
priority=10

[program:vscode]
command=code-server --bind-addr 127.0.0.1:8000 --auth password --user-data-dir /root/.config/code-server
environment=PASSWORD="%(ENV_VSCODE_PASSWORD)s"
autorestart=true
priority=10

# [program:npm-api]
# command=node /app/index.js
# directory=/app
# autorestart=true
# priority=10

# [program:npm-nginx]
# command=nginx -g "daemon off;"
# autorestart=true
# priority=10
